// GENERATED by scripts/build-brand.mjs from brands/lemonsqueezer/brand.json — do not edit by hand.
(function () {
  var BRAND = {
  "apiBrand": "lemonsqueezer",
  "displayName": "LemonSqueezer",
  "storeName": "LemonSqueezer — TL;DR",
  "tagline": "Skip the noise. Get the point.",
  "wordmark": {
    "pre": "Lemon",
    "accent": "Squeezer"
  },
  "primaryAction": "summarize",
  "heroMetric": "time_saved",
  "tokens": {
    "colors": {
      "primary": "#FFD400",
      "primary700": "#FFB800",
      "black": "#0D1117",
      "white": "#FFFFFF",
      "gray100": "#F2F4F7",
      "mint": "#22C55E",
      "red": "#EF4444"
    },
    "radius": "12px",
    "shadowSm": "0 2px 6px rgba(0,0,0,0.08)",
    "shadowMd": "0 8px 24px rgba(0,0,0,0.12)",
    "fontSans": "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
  }
};
  if (typeof globalThis !== 'undefined') globalThis.__BRAND__ = BRAND;
})();
